### ISSUE TITLE
在CentOS7.3 64bit(仅安装有LAMP)下 libsodium 安装失败

### ISSUE THREAD

**Issue by elfive1992** [onekeyshell/kcptun_for_ss_ssr#1]
安装的是ss-libev + kcptun
系统是CentOS 64位、仅安装了apache、mysql、php和phpMyAdmin；

我这只挑出最后相关错误的log

`+ Install libsodium for SS-Libev/SSR/KCPTUN
tar: 跳转到下一个头

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
configure: error: cannot find sources (src/libsodium/sodium/version.c) in . or ..
rm：无效选项 -- g
Try 'rm --help' for more information.
libsodium install failed!`

**Comment by onekeyshell** [comment]
感觉是解压出现了问题，重新安装一次试试
