### ISSUE TITLE
Centos yum 已经无法安装 mbedtls

### ISSUE THREAD

**Issue by sKyissKy** [onekeyshell/kcptun_for_ss_ssr#10]
一键脚本在安装 mbedtls时
提示
No package mbedtls-devel available.
mbedtls install failed!

**Comment by onekeyshell** [comment]
我试试，或者你换个系统试试

**Comment by benqiu** [comment]
我在搬瓦工也遇到这个问题，后来用debian的系统，里面自带mbedtls。
