### ISSUE TITLE
update功能似乎出问题了

### ISSUE THREAD

**Issue by zxszx** [onekeyshell/kcptun_for_ss_ssr#13]
我每次使用脚本的update都会检测出我的ssr是2.8.2最新版本是3.3.3 然后提示更新成功 启动后还是2.8.2
不确定是我操作有问题还是更新的有问题

**Comment by onekeyshell** [comment]
You have 5 options for your kcptun/ss/ssr update.
1: Update Shadowsocks-libev
2: Update ShadowsocksR(python)
3: Update KCPTUN
4: Update All
Exit (default)
Enter your choice (1, 2, 3, 4 or exit. default [exit]): 2

You will update ShadowsocksR(python)
Loading ShadowsocksR version, please wait...
+-------------------------------------------------------------+
ShadowsocksR shell version : 3.3.3
ShadowsocksR local version : 3.3.3
ShadowsocksR local version is up-to-date.

nothing to do...


没啥问题啊，卸载重装一下试试

**Comment by zxszx** [comment]
我的local version 是2.8.2 每次都会说发现新版本 然后我看提示也下载成功 并且解压进了/etc/init.d/
