### ISSUE TITLE
不能更新了

### ISSUE THREAD

**Issue by helllkz** [onekeyshell/kcptun_for_ss_ssr#16]
ubuntu下面

Err http://shadowsocks.org wheezy/main amd64 Packages  404  Not Found [IP: 104.28.18.85 80]
Err http://shadowsocks.org squeeze/main amd64 Packages  404  Not Found [IP: 104.28.18.85 80]
W: Failed to fetch http://shadowsocks.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found [IP: 104.28.18.85 80]
W: Failed to fetch http://shadowsocks.org/debian/dists/squeeze/main/binary-amd64/Packages  404  Not Found [IP: 104.28.18.85 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by onekeyshell** [comment]
你用脚本安装的么？感觉这个提示是系统的软件源的问题

**Comment by helllkz** [comment]
重装了下系统好像又对了，奇怪
