### ISSUE TITLE
SSR update issue

### ISSUE THREAD

**Issue by nickkilla** [onekeyshell/kcptun_for_ss_ssr#18]
You will update All                                                             
Loading ShadowsocksR version, please wait...                                    
Loading kcptun version, please wait...                                          
+-------------------------------------------------------------+                 
Shadowsocks-libev not install!                                                  
+-------------------------------------------------------------+                 
./kcptun_for_ss_ssr-install.sh: line 1601: ssr: command not found               
Error: Get ShadowsocksR shell version failed                                    
+-------------------------------------------------------------+                 
Kcptun shell version : 20170525                                                 
Kcptun local version : 20170525                                                 
Kcptun local version is up-to-date.                                             
                                                                                
nothing to do...

**Comment by onekeyshell** [comment]
看看你的软链是不是没了，/usr/local/bin/ssr这个位置，是软链的/etc/init.d/ssr

**Comment by onekeyshell** [comment]
ln -s /etc/init.d/ssr /usr/local/bin/ssr
