### ISSUE TITLE
ShadowsocksR无法从3.3.2更新到3.4.0

### ISSUE THREAD

**Issue by saikm01** [onekeyshell/kcptun_for_ss_ssr#25]
用./kcptun_for_ss_ssr-install.sh update升级ShadowsocksR

整个升级过程如下：

+-------------------------------------------------------------+
ShadowsocksR shell version : 3.4.0
ShadowsocksR local version : 3.3.2
+-------------------------------------------------------------+
Found a new version,update now...

Press any key to continue...or Press Ctrl+c to cancel

2017-09-21 09:21:07 INFO     shell.py:72 ShadowsocksR 3.3.2 2017-05-20
loaded collections.OrderedDict
IPv6 support
stopped
Stopping ShadowsocksR success
manyuser.zip [found]
--2017-09-21 09:21:07--  https://raw.githubusercontent.com/onekeyshell/kcptun_for_ss_ssr/master/ssr.init
Resolving raw.githubusercontent.com... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2176 (2.1K) [text/plain]
Saving to: `/etc/init.d/ssr'

     0K ..                                                    100% 14.4M=0s

2017-09-21 09:21:08 (14.4 MB/s) - `/etc/init.d/ssr' saved [2176/2176]

Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.hostduplex.com
 * epel: mirror.sjc02.svwh.net
 * extras: centos.sonn.com
 * updates: mirror.sigmanet.com
Package epel-release-6-8.noarch already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.hostduplex.com
 * epel: mirror.sjc02.svwh.net
 * extras: centos.sonn.com
 * updates: mirror.sigmanet.com
Package unzip-6.0-5.el6.i686 already installed and latest version
Package openssl-devel-1.0.1e-57.el6.i686 already installed and latest version
Package gcc-4.4.7-18.el6.i686 already installed and latest version
Package swig-1.3.40-6.el6.i686 already installed and latest version
Package autoconf-2.63-5.1.el6.noarch already installed and latest version
Package libtool-2.2.6-15.5.el6.i686 already installed and latest version
Package libevent-1.4.13-4.el6.i686 already installed and latest version
Package 2:vim-enhanced-7.4.629-5.el6_8.1.i686 already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package 1:make-3.81-23.el6.i686 already installed and latest version
Package psmisc-22.6-24.el6.i686 already installed and latest version
Package curl-7.19.7-53.el6_9.i686 already installed and latest version
Package libcurl-devel-7.19.7-53.el6_9.i686 already installed and latest version
Package zlib-devel-1.2.3-29.el6.i686 already installed and latest version
Package 4:perl-5.10.1-144.el6.i686 already installed and latest version
Package 4:perl-devel-5.10.1-144.el6.i686 already installed and latest version
Package cpio-2.10-13.el6.i686 already installed and latest version
Package expat-devel-2.0.1-13.el6_8.i686 already installed and latest version
Package gettext-devel-0.17-18.el6.i686 already installed and latest version
Package xmlto-0.0.23-3.el6.i686 already installed and latest version
Package asciidoc-8.4.5-4.1.el6.noarch already installed and latest version
Package pcre-7.8-7.el6.i686 already installed and latest version
Package pcre-devel-7.8-7.el6.i686 already installed and latest version
Package python-2.6.6-66.el6_8.i686 already installed and latest version
Package python-devel-2.6.6-66.el6_8.i686 already installed and latest version
Package python-setuptools-0.6.10-3.el6.noarch already installed and latest version
Package udns-devel-0.0.9-5.el6.i686 already installed and latest version
Package libev-devel-4.03-3.el6.i686 already installed and latest version
Package mbedtls-devel-2.6.0-1.el6.i686 already installed and latest version
Nothing to do
2017-09-21 09:21:10 INFO     util.py:85 loading libsodium from libsodium.so.18
2017-09-21 09:21:10 INFO     shell.py:72 ShadowsocksR 3.3.2 2017-05-20
loaded collections.OrderedDict
IPv6 support
Starting ShadowsocksR success
ShadowsocksR start success!
rm: invalid option -- 'g'
Try `rm --help' for more information.
rm: invalid option -- 'g'
Try `rm --help' for more information.

+----------------------------------------------------------------+
|                KCPTUN for SS/SSR on Linux Server               |
+----------------------------------------------------------------+
|  A tool to auto-compile & install KCPTUN for SS/SSR on Linux   |
+----------------------------------------------------------------+
| Intro: https://github.com/onekeyshell/kcptun_for_ss_ssr/issues |
+----------------------------------------------------------------+

Congratulations, update completed, Enjoy it!

最后ShadowsocksR的版本还是3.3.2，怎么办呢？谢谢！

**Comment by onekeyshell** [comment]
ssr不用看这个，实际上已经是3.4.0了
