### ISSUE TITLE
软件中心shadowsocks停止更新kcptun版本也停止更新

### ISSUE THREAD

**Issue by Baymaax** [onekeyshell/kcptun_for_ss_ssr#28]
shadowsocks内置的kcptun版本停留在0525但是服务端的一直在更新，导致开启kcp加速因为版本不同的原因国外PD，希望加一个kcptun版本回滚以统一客户端和服务端版本

**Comment by c932** [comment]
悲剧的脚本都被查封了。。。

**Comment by onekeyshell** [comment]
更新把
