### ISSUE TITLE
安装程序升级时出现错误。

### ISSUE THREAD

**Issue by SunZhizhong** [onekeyshell/kcptun_for_ss_ssr#7]
在安装程序升级shell后，此安装包不管是卸载、升级还是安装都会提示一下错误：
./kcptun_for_ss_ssr-install.sh: line 1296: syntax error near unexpected token `)'
./kcptun_for_ss_ssr-install.sh: line 1296: `            12|[Nn][Oo][Nn][Ee])'

**Comment by AbraxasVi** [comment]
1295行后面忘了俩分号！谁改的！大意了啊！！！

**Comment by onekeyshell** [comment]
已修复，请更新！
